### ISSUE TITLE
RTSP handshake problems after HA 0.57.1

### ISSUE THREAD

**Issue by wilfredsmit** [Kane610/axis#4]
After upgrading HA to 0.57.1 the following errors occur in home-assistant.log:

```
2017-11-04 18:43:03 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback _SelectorSocketTransport._read_ready()
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "/srv/homeassistant/lib/python3.5/site-packages/axis/rtsp.py", line 76, in data_received
    self.transport.write(self.method.message.encode())
  File "/srv/homeassistant/lib/python3.5/site-packages/axis/rtsp.py", line 190, in message
    message = self.message_methods[self.session.method]()
  File "/srv/homeassistant/lib/python3.5/site-packages/axis/rtsp.py", line 224, in SETUP
    message = "SETUP " + self.session.control_url + " RTSP/1.0\r\n"
TypeError: Can't convert 'NoneType' object to str implicitly
```

Using Hassbian v1.3, Axis M1031-W camera
Although the camera functioning well in HA.

**Comment by Kane610** [comment]
Thanks! But the issue is in the HASS component, please put the issue there.
